name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript type checking
      run: npx tsc --noEmit

    - name: Build check
      run: npm run build

    - name: Test execution
      run: |
        echo "Running tests..."
        # Set Jest to run in CI mode with specific configuration
        export CI=true
        export NODE_OPTIONS="--max-old-space-size=4096"
        
        # Try running tests with different configurations to handle potential issues
        if npm test -- --passWithNoTests --verbose --runInBand --forceExit; then
          echo "✅ Tests passed successfully"
        else
          echo "❌ Tests failed"
          echo "Attempting to run tests with alternative configuration..."
          
          # Fallback: try with minimal configuration
          if npx jest --passWithNoTests --runInBand --forceExit --no-cache; then
            echo "✅ Tests passed with fallback configuration"
          else
            echo "❌ Tests failed with all configurations"
            exit 1
          fi
        fi

  dependency-security:
    name: Security Audit
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=high
