name: Test Suite

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting (if available)
      run: |
        if npm run lint --silent 2>/dev/null; then
          echo "Running linting..."
          npm run lint
        else
          echo "No lint script found, skipping linting"
        fi
      continue-on-error: true

    - name: Run type checking
      run: |
        if npm run type-check --silent 2>/dev/null; then
          echo "Running type checking..."
          npm run type-check
        else
          echo "Running TypeScript compiler check..."
          npx tsc --noEmit
        fi

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build project
      run: npm run build

  test-coverage:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm test -- --coverage --watchAll=false
      env:
        CI: true

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
      with:
        fail_ci_if_error: false
